### ISSUE TITLE
__init__() got an unexpected keyword argument 'adapter_kwargs'

### ISSUE THREAD

**Issue by bocchris-aws** [huggingface/optimum-neuron#256]
When I try to run `run_summarization.py` from the main branch, I run into the following error:

```
Traceback (most recent call last):                                                                                                                                                                                                                                                                                │··
    return func(*args, **kwargs)                                                                                                                                                                                                                                                                                  │··
  File "/home/ubuntu/optimum-neuron/optimum/neuron/distributed/utils.py", line 552, in from_pretrained_for_tp                                                                                                                                                                                                     │··
  File "run_summarization.py", line 757, in <module>                                                                                                                                                                                                                                                              │··
    model = cls(config, *model_args, **model_kwargs)                                                                                                                                                                                                                                                              │··
TypeError: __init__() got an unexpected keyword argument 'adapter_kwargs'                                                                                                                                                                                                                                         │··
    main()                                                                                                                                                                                                                                                                                                        │··
  File "run_summarization.py", line 433, in main                                                                                                                                                                                                                                                                  │··
    model = AutoModelForSeq2SeqLM.from_pretrained(                                                                                                                                                                                                                                                                │··
  File "/opt/aws_neuron_venv_pytorch/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 565, in from_pretrained                                                                                                                                                                          │··
    return model_class.from_pretrained(                                                                                                                                                                                                                                                                           │··
  File "/home/ubuntu/optimum-neuron/optimum/neuron/utils/require_utils.py", line 44, in wrapper                                                                                                                                                                                                                   │··
    return func(*args, **kwargs)                                                                                                                                                                                                                                                                                  │··
  File "/home/ubuntu/optimum-neuron/optimum/neuron/distributed/utils.py", line 552, in from_pretrained_for_tp                                                                                                                                                                                                     │··
    model = cls(config, *model_args, **model_kwargs)                                                                                                                                                                                                                                                              │··
TypeError: __init__() got an unexpected keyword argument 'adapter_kwargs'
```

Transformers is at `4.34.0` and was installed as dependency during installation of `optimum-neuron`.

**Comment by bocchris-aws** [comment]
Code works with `transformers==4.33.1`.

**Comment by michaelbenayoun** [comment]
Fixed by #259 .
Please re-open if the issue persists.
