### ISSUE TITLE
ErrorMessage "TypeError: _TrainerForNeuron.compute_loss() got an unexpected keyword argument 'return_outputs'

### ISSUE THREAD

**Issue by weicch** [huggingface/optimum-neuron#787]
### System Info

```shell
I've created HuggingFace estimator with different image to create container. I've also installed optimum-neuron and transformer version in the environment. And plan to create train job on Sagemaker. Previous optimum-neuron==0.0.26 work successfully. HHowever, I saw below the compute_loss version mismatch issue after I migrate to 0.0.28.

optimum-neuron==0.0.28
transformer==4.48.1
tried image_uri : [
763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-training-neuronx:2.5.1-neuronx-py310-sdk2.21.0-ubuntu22.04,
763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-training-neuronx:2.1.2-neuronx-py310-sdk2.20.2-ubuntu20.04,
763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-training-neuronx:2.1.2-neuronx-py310-sdk2.19.1-ubuntu20.04,
]

Train model: Llama3.1-8B-instruct
```

### Who can help?

Transformer: [compute_loss has return_outpus parameter](https://github.com/huggingface/transformers/blob/v4.48.1/src/transformers/trainer.py#L4483)

trainers in optimum-neruon [compute_loss](https://github.com/huggingface/optimum-neuron/blob/main/optimum/neuron/trainers.py#L404) did not expect new introduced return_outpus parameter.

**Error Message:**
`ErrorMessage "TypeError: _TrainerForNeuron.compute_loss() got an unexpected keyword argument 'return_outputs'
 ERROR:__main__:Error during training: _TrainerForNeuron.compute_loss() got an unexpected keyword argument 'return_outputs'
 Traceback (most recent call last)
 File "/opt/ml/code/finetune_trn1.py", line 336, in training_function
 execute_training(trainer, training_args, model_config)
 File "/opt/ml/code/finetune_trn1.py", line 227, in execute_training
 trainer.train(resume_from_checkpoint=checkpoint)
 File "/usr/local/lib/python3.10/site-packages/optimum/neuron/trainers.py", line 1802, in train
 output = super().train(*args, **kwargs)
 File "/usr/local/lib/python3.10/site-packages/optimum/neuron/trainers.py", line 1467, in train
 result = super().train(
 File "/usr/local/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 434, in train
 File "/usr/local/lib/python3.10/site-packages/transformers/trainer.py", line 2171, in train
 return inner_training_loop(
 File "/usr/local/lib/python3.10/site-packages/optimum/neuron/utils/require_utils.py", line 52, in wrapper
 return func(*args, **kwargs)
 File "/usr/local/lib/python3.10/site-packages/optimum/neuron/trainers.py", line 1148, in _inner_training_loop
 self._maybe_log_save_evaluate(tr_loss, grad_norm, model, trial, epoch, ignore_keys_for_eval)
 File "/usr/local/lib/python3.10/site-packages/optimum/neuron/trainers.py", line 536, in _maybe_log_save_evaluate
 metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
 File "/usr/local/lib/python3.10/site-packages/optimum/neuron/trainers.py", line 1485, in evaluate
 result = super().evaluate(
 File "/usr/local/lib/python3.10/site-packages/transformers/trainer.py", line 4073, in evaluate
 output = eval_loop(
 File "/usr/local/lib/python3.10/site-packages/optimum/neuron/trainers.py", line 1337, in evaluation_loop
 loss, logits, labels = self.prediction_step(model, inputs, prediction_loss_only, ignore_keys=ignore_keys)
 File "/usr/local/lib/python3.10/site-packages/optimum/neuron/trainers.py", line 467, in prediction_step
 return super().prediction_step(model, inputs, prediction_loss_only, ignore_keys=ignore_keys)
 File "/usr/local/lib/python3.10/site-packages/transformers/trainer.py", line 4483, in prediction_step
 loss, outputs = self.compute_loss(model, inputs, return_outputs=True)
 File "/opt/ml/code/finetune_trn1.py", line 366, in <module>
 training_function(script_args, training_args, model_config)
 execute_training(trainer, training_args, model_config)    training_function(script_args, training_args, model_config)
 training_function(script_args, training_args, model_config)Traceback (most recent call last)`

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

1. Create huggingface estimator with any container image url.
2. Install below library
optimum-neuron==0.0.28
transformer==4.48.1
3. trigger the training job on trn1 instance.

I've point to the specific code of conflict. If you have any question, please let me know. 

### Expected behavior

Can train llama3.1-8B-Instruct with latest optimum-neuron library successfully.

**Comment by michaelbenayoun** [comment]
It should be fixed by #774 [here](https://github.com/huggingface/optimum-neuron/pull/774/files#diff-ce0b61a451523d0f154da7f53896ae9a3b3933a6190dae00db87c4b14f19dd33R416).

**Comment by weicch** [comment]
Hi @michaelbenayoun, thanks for the pointer for this PR and fix. Feel free to close this issue when this PR merged.

**Comment by weicch** [comment]
The issue resolved in 0.1.0 version. Thanks @michaelbenayoun
